### ISSUE TITLE
Roller on both sides?

### ISSUE THREAD

**Issue by BigBlueHat** [zzeneg/smol#1]
First, thanks for building this design! I'm hoping to build it out for my next board.

Second, I was wondering if there were technical limitations that prevented a roller encoder on both sides, or if the initial design just didn't support it.

In my head, I'd like to have two--one left-to-right and one up-to-down--for page scrolling/mouse-wheel (with modifier).

Just curious if it is conceivably possible or if there's some key limitation that'd be hard to overcome.

Sorry for the newbie question, and thanks again for sharing!

Cheers!
🎩

**Comment by BigBlueHat** [comment]
Ah...it's the reversible PCB...

I might just need to make my peace with having a (hopefully low profile) rotary there instead.

Maybe in a non-reversible version 2? 😉 

Thanks again for building and sharing this design!

**Comment by zzeneg** [comment]
Hey, yes - it's reversible, so I don't think it's possible to make the roller footprint reversible and have enough space for routing.
If you really want it, you could just copy existing PCB, flip that footprint and order two sets of PCBs for left and right sides. But the goal of that board was to be as cheap as possible, and in my mind it's not justified to put two roller encoders on it when even one is more expensive that all PCBs :) I'd say there are more comfortable designs if you can afford to spend more money.

**Comment by BigBlueHat** [comment]
Completely agree. 😃
